In [1]:
import numpy as np
from sklearn import mixture

In [6]:
g = mixture.GaussianMixture(n_components=3, covariance_type='full',
                             random_state=0, init_params='random', n_init=5) #'kmeans')
data = np.random.rand(10000, 14)
g.fit(data)


GaussianMixture(covariance_type='full', init_params='random', max_iter=100,
        means_init=None, n_components=3, n_init=5, precisions_init=None,
        random_state=0, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [7]:
prob = g.predict_proba(data)
print prob

[[0.32239039 0.3208235  0.35678611]
 [0.34832858 0.30890007 0.34277135]
 [0.31824482 0.35278807 0.32896712]
 ...
 [0.28850528 0.33649306 0.37500166]
 [0.30110068 0.33293341 0.36596592]
 [0.3574302  0.31462541 0.32794439]]
